[versions]
# 核心插件版本 (同步 OShin)
agp = "8.12.3"
kotlin = "2.2.21"
ksp = "2.2.20-2.0.3"

# 依赖库版本
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.14.0-alpha09"
constraintlayout = "2.2.1"

# Compose 相关
compose-bom = "2025.10.01"

[libraries]
# 核心库
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# Compose BOM
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }

# Xposed & YukiHook API
xposed-api = { group = "de.robv.android.xposed", name = "api", version = "82" }
yukihook-api = { group = "com.highcapable.yukihookapi", name = "api", version = "1.3.1" }
yukihook-ksp-xposed = { group = "com.highcapable.yukihookapi", name = "ksp-xposed", version = "1.3.1" }

[plugins]
# 核心插件
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
